const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/chenss77/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge' });
  const errors = [];
  const failedRequests = [];
  let checks = 0;
  let transitionCaptured = false;
  const introChecked = new Set();
  const introExpected = { hub: ['01', 'HIDEOUT', '据点'], events: ['02', 'MISSION SELECT', '选择行动'], community: ['03', 'BUILD YOUR BONDS', '建立羁绊'], me: ['04', 'PERSONAL RECORD', '个人档案'] };
  const check = (value, message) => {
    assert.ok(value, message);
    checks += 1;
    console.log('PASS', message);
  };
  const open = async (viewport, hash = '') => {
    const page = await browser.newPage({ viewport });
    page.on('pageerror', error => errors.push(error.message));
    page.on('requestfailed', request => failedRequests.push(`${request.url()} :: ${request.failure()?.errorText || 'failed'}`));
    await page.goto(pathToFileURL(path.join(__dirname, 'index.html')).href + hash);
    await page.waitForTimeout(900);
    return page;
  };
  const switchPage = async (page, route) => {
    await page.locator(`[data-route="${route}"]`).first().click();
    check(await page.locator('#transition').evaluate(el => el.classList.contains('play')), `切换到 ${route} 时转场可见`);
    await page.waitForTimeout(360);
    if (!transitionCaptured) {
      await page.screenshot({ path: path.join(__dirname, 'transition.png') });
      transitionCaptured = true;
    }
    await page.waitForTimeout(500);
    await page.waitForSelector(`.${route === 'hub' ? 'hub-screen' : route === 'events' ? 'events-screen' : route === 'community' ? 'community-screen' : 'me-screen'}`);
    const introMode = page.viewportSize().width <= 700 ? 'mobile' : 'desktop';
    const introKey = `${route}-${introMode}`;
    if (!introChecked.has(introKey)) {
      const intro = page.locator('#page-intro');
      check(await intro.evaluate(el => el.classList.contains('show') && el.getAttribute('aria-hidden') === 'false'), `${introMode} ${route} 页面进入提示在转场结束后显示`);
      const introText = await intro.innerText();
      check(introExpected[route].every(text => introText.includes(text)), `${introMode} ${route} 页面进入提示使用正确页码与主题文案`);
      check(!await page.locator('#transition').evaluate(el => el.classList.contains('play')), `${introMode} ${route} 页面进入提示不会与切页转场重叠`);
      await page.waitForTimeout(260);
      if (route === 'events' && introMode === 'desktop') await page.screenshot({ path: path.join(__dirname, 'page-intro-desktop.png'), fullPage: false });
      if (route === 'events' && introMode === 'mobile') {
        check(await intro.evaluate(el => el.getBoundingClientRect().width <= innerWidth && el.getBoundingClientRect().bottom <= innerHeight), '移动端页面进入提示不超出 390px 视口');
        check(await intro.evaluate(el => getComputedStyle(el).pointerEvents === 'none'), '移动端页面进入提示不阻塞底部 COMMAND');
        await page.screenshot({ path: path.join(__dirname, 'page-intro-mobile.png'), fullPage: false });
      }
      introChecked.add(introKey);
    }
    await page.waitForFunction(() => document.querySelector('#page-intro').getAttribute('aria-hidden') === 'true', null, { timeout: 2200 });
  };

  try {
    const page = await open({ width: 1440, height: 1080 });
    check((await page.locator('h1').first().innerText()).includes('放学后'), '据点首屏加载');
    check(await page.locator('html').getAttribute('data-theme') === 'p5', '根节点启用 P5 主题标识');
    check(await page.evaluate(() => Object.keys(window.CLUB_THEMES).length >= 3 && window.CLUB_THEMES.p5.id === 'p5' && window.CLUB_THEMES['blue-archive'].id === 'blue-archive' && ['p5','blue-archive','neon-grid'].every(id => window.CLUB_THEMES[id].rights.status === 'cleared' && window.CLUB_THEMES[id].rights.confirmedAt === '2026-09-24' && window.CLUB_THEMES[id].rights.evidenceStatus === 'owner-confirmed-not-reproduced-in-repository')), '三主题授权状态反映负责人确认并保留凭证未入库边界');
    check(await page.evaluate(() => { const theme = window.CLUB_THEMES['neon-grid']; const result = window.CLUB_THEME_RUNTIME.validate(theme); return !!theme && result.valid && theme.status === 'active-local' && theme.motion.transition === 'neon-scan' && theme.pageIntros.me.code === 'USER CONSOLE'; }), '第三主题只通过注册表与表现 profile 接入，四页契约完整');
    check(await page.evaluate(() => { const result = window.CLUB_THEME_RUNTIME.apply('neon-grid'); const active = document.documentElement.dataset.theme === 'neon-grid'; const tokens = result.missingCssTokens.length === 0; const motion = document.documentElement.dataset.themeMotion === 'neon-scan'; window.CLUB_THEME_RUNTIME.apply('p5'); return active && tokens && motion && document.documentElement.dataset.theme === 'p5'; }), '第三主题可切换、令牌完整并可安全回退 P5');
    check(await page.evaluate(() => window.CLUB_THEME_CONTRACT.schemaVersion === 1 && window.CLUB_THEME_CONTRACT.pageIds.join(',') === 'hub,events,community,me'), '主题包 v1 契约固定四个一级页面与版本');
    check(await page.evaluate(() => document.documentElement.dataset.themeVersion === '1.0.0' && document.documentElement.dataset.themeSchema === '1'), '根节点记录实际主题包版本与契约版本');
    check(await page.evaluate(() => { const result = window.CLUB_THEME_RUNTIME.inspect('p5'); return result.valid && result.applied && result.missingCssTokens.length === 0; }), 'P5 主题元数据与全部必需 CSS 令牌通过运行时校验');
    check(await page.evaluate(() => { const result = window.CLUB_THEME_RUNTIME.validate({ id: 'broken theme' }); return !result.valid && result.errors.some(error => error.includes('pageIntros.hub')) && result.errors.some(error => error.includes('rights.status')); }), '候选主题缺失元数据或页面文案时会被拒绝');
    check(await page.evaluate(() => { const result = window.CLUB_THEME_RUNTIME.inspect('not-installed'); return !result.valid && result.usedFallback && result.id === 'p5'; }), '未安装主题按契约回退 P5，不复制业务逻辑');
    check(await page.evaluate(() => window.CLUB_THEMES.p5.rights.status === 'cleared' && window.CLUB_THEMES.p5.rights.records.length === 3 && window.CLUB_THEMES.p5.rights.evidenceStatus === 'owner-confirmed-not-reproduced-in-repository'), 'P5 主题保留负责人授权确认与来源记录');
    check(await page.evaluate(() => window.CLUB_THEMES.p5.assets.audio === 'assets/p5/audio/'), 'P5 主题音频根目录已迁入 club-app');
    check(await page.locator('#transition-video').getAttribute('preload') === 'none', '非首屏转场视频不再参与初始自动预载');
    check(await page.evaluate(() => document.querySelectorAll('link[rel="preload"][href*="assets/feedback"]').length === 0 && document.querySelector('#loader img').getAttribute('src') === 'assets/visual/loader-stars.webp'), '交互反馈图片退出首屏预载且加载动画使用轻量派生资源');
    check(['index.html', 'app.js', 'styles.css', 'theme-registry.js', 'build-visual-assets.py', 'inspect-site-videos.cjs'].every(file => !fs.readFileSync(path.join(__dirname, file), 'utf8').includes('p5-website')), '运行时与构建脚本不再引用 p5-website');
    const appSource = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
    const adapterSource = fs.readFileSync(path.join(__dirname, 'supabase-adapter.js'), 'utf8');
    const managementSql = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'enable-leader-event-management.sql'), 'utf8');
    const registrationManagementSql = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'enable-leader-event-registration-management.sql'), 'utf8');
    const leaderClubSql = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'enable-leader-club-management.sql'), 'utf8');
    const transferSql = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'enable-leader-club-transfer.sql'), 'utf8');
    check(appSource.includes('id="profile-form"') && appSource.includes('backend.updateProfile(nickname)'), '登录后账号面板提供昵称修改并提交真实资料更新');
    check(adapterSource.includes('backend.updateProfile=async nickname') && adapterSource.includes("from('users').update({nickname:next})"), '昵称修改通过 Supabase users 自有资料更新并复读 profile');
    check(appSource.includes("${isSignup?'<label class=\"field\">昵称") && !appSource.includes('auth-nickname'), '登录表单不渲染昵称输入，注册表单保留昵称输入');    check(appSource.includes('edit-leader-club') && appSource.includes('leader-club-edit-form') && appSource.includes('delete-leader-club'), 'leader club profile exposes rename and archive actions');
    check(adapterSource.includes("rpc('rename_leader_club'") && adapterSource.includes("rpc('archive_leader_club'"), 'club rename and archive use dedicated Supabase RPCs');
    check(leaderClubSql.includes('is_club_staff(target_club_id)') && leaderClubSql.toLowerCase().includes('for update'), 'club profile RPCs lock the target and enforce staff permission');
    check(leaderClubSql.includes("set status = 'archived'") && leaderClubSql.includes("set status = 'left'") && leaderClubSql.includes('confirmation_name'), 'club removal archives with explicit name confirmation and releases active membership');
    check(leaderClubSql.toLowerCase().includes('revoke execute') && leaderClubSql.toLowerCase().includes('grant execute') && leaderClubSql.includes('authenticated'), 'club profile RPC execution is limited to authenticated users');
    check(transferSql.includes('security definer') && transferSql.includes('set search_path = pg_catalog, public') && transferSql.includes('auth.uid() is null'), 'leadership transfer RPCs use a constrained security-definer boundary');
    check(transferSql.includes("cm.status = 'active'") && transferSql.includes("cm.role = 'member'") && transferSql.includes('cm.user_id <> auth.uid()'), 'transfer candidates are limited to other active members of the target club');
    check(transferSql.includes('is_club_staff(target_club_id)') && transferSql.toLowerCase().includes('for update') && transferSql.includes('confirmation_name'), 'transfer requires target-club staff authorization, row locks and exact club-name confirmation');
    check(transferSql.includes("set role = 'member'") && transferSql.includes("set role = 'leader'") && transferSql.includes('unique_violation'), 'transfer atomically demotes the previous leader and rolls back conflicting cross-club leaders');
    check(transferSql.includes('club_leadership_transfers') && transferSql.includes('enable row level security') && transferSql.includes('revoke all on table'), 'transfer audit history is protected from browser table access');
    check(transferSql.toLowerCase().includes('revoke execute') && transferSql.toLowerCase().includes('grant execute') && transferSql.includes('authenticated'), 'transfer RPC execute privileges exclude public and anon');
    check(adapterSource.includes("rpc('list_club_lead_transfer_candidates'") && adapterSource.includes("rpc('transfer_club_leadership'") && !/from\(['"]club_members['"]\)\.(?:update|delete)/.test(appSource), 'leadership changes use secure RPCs without direct browser membership updates');
    check(appSource.includes('原社长已降为普通 member') && appSource.includes('pending、rejected、left、admin、其他社团负责人均不符合') && appSource.includes('transfer.status===\'permission-denied\''), 'transfer UI explains the demotion rule and exposes empty/error/permission-denied states');    check(appSource.includes("state.authStatus==='authenticated'?'创建你的社团'") && appSource.includes("p5btn('创建新社团','create-club','','red')"), 'authenticated users without a leader club see create-club state, not a dead management preview');
    check(appSource.includes('liveClubs.length>1?') && appSource.includes('leader-current-club'), 'single leader club is static while multiple manageable clubs retain a selector');
    check(!/from\(['"]clubs['"]\)\.(?:update|delete)/.test(appSource), 'browser never directly updates or deletes clubs');
    check(appSource.includes('leader-event-edit-form') && appSource.includes('leader-edit-event') && appSource.includes('leader-cancel-event'), 'leader console exposes event edit and cancel semantics');
    check(appSource.includes("['roster','活动详情']") && !appSource.includes("['roster','报名名单']"), 'leader console renames roster tab to activity details');
    check(appSource.includes('活动已取消') && appSource.includes('已取消活动保留报名历史，只读查看'), 'cancelled events keep roster history and become read-only');
    check(appSource.includes('backend.updateLeaderEvent({target_event_id:id') && appSource.includes('backend.cancelLeaderEvent(id)'), 'browser management actions go through Supabase RPC adapter');
    check(!/from\(['"]events['"]\)\.update|from\(['"]event_details['"]\)\.update/.test(appSource), 'browser never directly updates events or event_details tables');
    check(adapterSource.includes("rpc('update_leader_event'") && adapterSource.includes("rpc('cancel_leader_event'"), 'adapter registers event management RPCs');
    check(appSource.includes('leader-promote-participant') && appSource.includes('leader-cancel-participant') && appSource.includes('window.prompt'), 'real roster exposes reason-required leader participant actions');
    check(appSource.includes('backend.promoteWaitlistedParticipant(id,reason)') && appSource.includes('backend.cancelEventParticipantByLeader(id,reason)'), 'real participant actions go through dedicated Supabase RPC adapter methods');
    check(appSource.includes("m.rawStatus==='waitlisted'") && appSource.includes("m.rawStatus==='confirmed'") && !appSource.includes("m.rawStatus==='cancelled'?`<button"), 'cancelled real roster records remain read-only and status-distinct');
    check(adapterSource.includes("rpc('promote_waitlisted_participant'") && adapterSource.includes("rpc('cancel_event_participant_by_leader'"), 'adapter registers participant management RPCs');
    check(registrationManagementSql.includes('event_participant_management_log') && registrationManagementSql.includes('promote_waitlisted_participant') && registrationManagementSql.includes('cancel_event_participant_by_leader'), 'registration management SQL provides audit table and secure RPCs');
    check(registrationManagementSql.includes('for update') && registrationManagementSql.includes('is_club_staff') && registrationManagementSql.includes('action_reason') && registrationManagementSql.includes('from_status') && registrationManagementSql.includes('to_status'), 'registration RPCs lock rows, check staff permission and write reasoned audit transitions');
    check(registrationManagementSql.includes('revoke execute') && registrationManagementSql.includes('grant execute') && registrationManagementSql.includes('authenticated'), 'registration RPC execute permissions are restricted to authenticated users');
    check(managementSql.includes('create or replace function public.update_leader_event') && managementSql.includes('create or replace function public.cancel_leader_event'), 'management SQL provides secure edit and cancel RPCs');
    check(managementSql.includes('is_club_staff(target.club_id)') && managementSql.includes('没有该社团的活动编辑权限') && managementSql.includes('没有该社团的活动取消权限'), 'management RPCs delegate to active leader/admin club permission guard');
    check(managementSql.includes('confirmed_total') && managementSql.includes('event_capacity < confirmed_total'), 'management SQL validates confirmed capacity constraint');
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'desktop base layout has no horizontal overflow after management integration');
    check(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--theme-events-background').includes('mission-city.webp') && getComputedStyle(document.documentElement).getPropertyValue('--theme-profile-background').includes('profile-dossier.webp')), '一级页面背景通过主题资源令牌接入');
    check(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--theme-accent').trim() === '#d60024'), 'P5 主题语义色令牌已生效');
    check(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--theme-status-pending').trim() === '#6d5dfc' && getComputedStyle(document.documentElement).getPropertyValue('--theme-status-locked').trim() === '#555555'), '状态颜色通过主题语义令牌提供，未来主题可独立覆盖');
    const p5Mobile = await open({ width: 390, height: 844 });
    check(await p5Mobile.locator('.menu-trigger').evaluate(el => {
      const menu = el.getBoundingClientRect();
      const nav = document.querySelector('.command-nav').getBoundingClientRect();
      const hit = document.elementFromPoint(menu.left + menu.width / 2, menu.top + menu.height / 2);
      return getComputedStyle(el).display !== 'none' && menu.width > 0 && menu.bottom <= innerHeight && menu.bottom < nav.top && (hit === el || el.contains(hit));
    }), 'P5 移动端 MENU 菜单入口可见且位于 COMMAND 上方且未被遮挡');
    await p5Mobile.locator('.menu-trigger').click();
    check(await p5Mobile.locator('#dialog').evaluate(el => el.open), 'P5 移动端 MENU 可以打开主题菜单');
    check(await p5Mobile.locator('.theme-choice[data-id="p5"]').count() === 1 && await p5Mobile.locator('.theme-choice[data-id="blue-archive"]').count() === 1, '移动端主题菜单提供 P5 与 Blue Archive 选项');
    await p5Mobile.locator('.theme-choice[data-id="blue-archive"]').click();
    check(await p5Mobile.locator('html').getAttribute('data-theme') === 'blue-archive', '移动端 MENU 可实际切换到 Blue Archive');
    await p5Mobile.locator('.menu-trigger').click();
    await p5Mobile.locator('.theme-choice[data-id="p5"]').click();
    check(await p5Mobile.locator('html').getAttribute('data-theme') === 'p5', '移动端 MENU 可从 Blue Archive 切回 P5');
    await p5Mobile.close();
    const baMobile = await open({ width: 390, height: 844 });
    await baMobile.evaluate(() => window.CLUB_THEME_RUNTIME.apply('blue-archive'));
    await baMobile.locator('[data-route="community"]').click();
    await baMobile.waitForTimeout(450);
    check(await baMobile.locator('.menu-trigger').evaluate(el => {
      const menu = el.getBoundingClientRect();
      const nav = document.querySelector('.command-nav').getBoundingClientRect();
      const advisor = document.querySelector('.advisor'); const hit = document.elementFromPoint(menu.left + menu.width / 2, menu.top + menu.height / 2); return getComputedStyle(el).display !== 'none' && menu.width > 0 && menu.bottom <= innerHeight && menu.bottom < nav.top && (!advisor || getComputedStyle(advisor).display === 'none') && (hit === el || el.contains(hit));
    }), 'BA 移动端 MENU 菜单入口可见且位于 COMMAND 上方且未被遮挡');
    check(await baMobile.locator('.advisor').evaluate(el => getComputedStyle(el).display === 'none'), 'BA 主题移除右下角顾问对话框');
    check(await baMobile.locator('.squad-panel').evaluate(el => {
      const style = getComputedStyle(el);
      return style.color === 'rgb(23, 50, 77)' && style.backgroundColor !== 'rgba(0, 0, 0, 0)';
    }), 'BA 同好页临时活动小队使用浅色高对比度面板');
    check(await baMobile.locator('[data-group-id="g2"]').evaluate(el => {
      const parse = value => (value.match(/[\d.]+/g) || []).slice(0, 3).map(Number);
      const luminance = value => { const rgb = parse(value).map(channel => { const c = channel / 255; return c <= .03928 ? c / 12.92 : ((c + .055) / 1.055) ** 2.4; }); return .2126 * rgb[0] + .7152 * rgb[1] + .0722 * rgb[2]; };
      const style = getComputedStyle(el); const foreground = luminance(style.color); const background = luminance(style.backgroundColor); return (Math.max(foreground, background) + .05) / (Math.min(foreground, background) + .05) >= 4.5;
    }), 'BA 王者荣耀同好卡片文字对比度至少达到 4.5:1');
    check(await baMobile.locator('[data-group-id="g2"] h2').evaluate(el => getComputedStyle(el).color === 'rgb(23, 50, 77)' && getComputedStyle(el.parentElement.querySelector('p')).color === 'rgb(53, 95, 123)'), 'BA 未加入社团卡片使用明确深色文字');
    check(await baMobile.locator('[data-group-id="g1"] h2').evaluate(el => getComputedStyle(el).color === 'rgb(255, 255, 255)' && getComputedStyle(el.parentElement.querySelector('p')).color === 'rgb(217, 245, 255)'), 'BA 已加入社团卡片使用明确浅色文字');
    await baMobile.close();    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '桌面无横向溢出');
    check(await page.locator('.command-nav a').count() === 4, '四个 COMMAND 主入口齐全');
    check(await page.locator('.hero-video').count() === 1, '据点使用全屏视频背景');
    check(await page.locator('#loader').evaluate(el => el.classList.contains('hide')), 'P5 加载层正常退场');
    check(await page.locator('img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0)), '据点图片资源可加载');
    check(await page.locator('html').getAttribute('lang') === 'zh-CN', '页面语言声明为 zh-CN');
    check(await page.locator('.skip').getAttribute('href') === '#main' && await page.locator('#main').getAttribute('tabindex') === '-1', '跳过链接与主内容锚点可用');
    check(await page.locator('#dialog').getAttribute('aria-label') === '弹出窗口' && await page.locator('#dialog').getAttribute('aria-labelledby') === null, '基础弹窗在关闭态仍有可计算名称');
    await page.screenshot({ path: path.join(__dirname, 'desktop.png'), fullPage: true });
    for (let i = 0; i < 8 && !await page.evaluate(() => document.activeElement?.id === 'sound-toggle'); i += 1) await page.keyboard.press('Tab');
    check(await page.evaluate(() => document.activeElement?.id === 'sound-toggle'), '键盘 Tab 可到达 HUD 声音按钮');
    check(await page.locator('#sound-toggle').evaluate(el => { const style = getComputedStyle(el); return style.outlineStyle !== 'none' && parseFloat(style.outlineWidth) >= 3 && style.boxShadow !== 'none'; }), '统一 focus-visible 提供高对比双层焦点环');

    // Message flow under test: HUD inbox -> filter/read/mark -> notice opening -> explicit confirmation.
    const inbox = await open({ width: 1440, height: 900 });
    check((await inbox.locator('.mail').getAttribute('aria-label')).includes('4 条未读'), 'HUD 显示演示消息未读数');
    await inbox.locator('[data-action="notice"]').click();
    check((await inbox.locator('#dialog-body').innerText()).includes('阅读并明确确认'), '据点公告入口仍可打开并要求明确确认');
    await inbox.locator('[data-action="close"]').last().click();
    await inbox.locator('.mail').focus();
    await inbox.locator('.mail').click();
    check(await inbox.locator('#dialog').getAttribute('aria-labelledby') === 'dialog-title' && await inbox.locator('#dialog-title').count() === 1, '打开弹窗后标题与 aria-labelledby 对齐');
    check(await inbox.locator('#dialog').evaluate(el => el.contains(document.activeElement)), '打开弹窗后焦点进入弹窗');
    await inbox.keyboard.press('Escape');
    check(!await inbox.locator('#dialog').evaluate(el => el.open) && await inbox.locator('.mail').evaluate(el => document.activeElement === el), 'Escape 关闭后焦点返回消息入口');
    await inbox.locator('.mail').click();
    check(await inbox.locator('.message-filters button').count() === 5, '消息中心五类指挥标签加载');
    check(await inbox.locator('.message-card').count() === 4, '消息中心明确展示四条演示线索');
    await inbox.screenshot({ path: path.join(require('node:os').tmpdir(), 'p5-inbox-desktop.png') });
    await inbox.locator('[data-action="message-filter"][data-id="活动"]').click();
    check(await inbox.locator('.message-card').count() === 1, '活动消息分类有效');
    await inbox.locator('[data-action="message-mark-visible"]').click();
    check((await inbox.locator('.message-toolbar').innerText()).includes('0 条未读'), '当前分类可批量标为已读');
    const disabledBatch = inbox.locator('[data-action="message-mark-visible"]');
    check(await disabledBatch.isDisabled() && await disabledBatch.getAttribute('aria-disabled') === 'true' && await disabledBatch.getAttribute('data-state') === 'LOCKED', '无未读时批量操作进入明确 LOCKED 状态');
    check((await inbox.locator('#message-batch-state').innerText()).includes('没有待处理的未读线索'), '禁用操作同时展示可读原因');
    const unreadAfterBatch = await inbox.locator('.mail').getAttribute('aria-label');
    await disabledBatch.evaluate(button => button.dispatchEvent(new MouseEvent('click', { bubbles: true })));
    check(await inbox.locator('.mail').getAttribute('aria-label') === unreadAfterBatch, 'disabled 与 aria-disabled 操作不会再次触发业务动作');
    check((await inbox.locator('.mail').getAttribute('aria-label')).includes('3 条未读'), '分类批量已读不会影响其他线索');
    await inbox.locator('[data-action="message-filter"][data-id="系统"]').click();
    await inbox.locator('[data-action="message-detail"][data-id="notice-n1"]').click();
    check((await inbox.locator('.message-reading').innerText()).includes('阅读这条消息不会自动确认公告'), '消息详情与公告确认语义分离');
    await inbox.locator('[data-action="message-target"]').click();
    check((await inbox.locator('#dialog-body').innerText()).includes('阅读并明确确认'), '打开公告之后仍须明确确认');
    await inbox.locator('[data-action="messages"]').last().click();
    check((await inbox.locator('.message-card').innerText()).includes('待明确确认'), '已读消息仍显示公告待确认');
    await inbox.locator('[data-action="message-detail"][data-id="notice-n1"]').click();
    await inbox.locator('[data-action="message-target"]').click();
    await inbox.locator('[data-action="confirm-notice"]').click();
    await inbox.locator('.mail').click();
    check((await inbox.locator('.message-card').innerText()).includes('已明确确认'), '明确确认后消息状态同步');
    await inbox.locator('[data-action="close"]').last().click();
    await inbox.waitForFunction(() => !document.querySelector('#toast').classList.contains('show'), null, { timeout: 4500 });
    await switchPage(inbox, 'events');
    await inbox.waitForFunction(() => document.querySelector('#page-intro').getAttribute('aria-hidden') === 'true', null, { timeout: 2200 });
    check(!await inbox.locator('#page-intro').evaluate(el => el.classList.contains('show')), '页面进入提示会自动退场');
    await inbox.locator('[data-action="event"][data-id="e1"]').click();
    await inbox.locator('[data-action="register"][data-id="e1"]').click();
    await inbox.locator('[data-action="close"]').last().click();
    await inbox.locator('.mail').click();
    await inbox.locator('[data-action="message-filter"][data-id="活动"]').click();
    check((await inbox.locator('.message-list').innerText()).includes('活动报名已确认'), '本次报名操作生成分类消息');
    await inbox.close();
    await switchPage(page, 'events');
    check(page.url().endsWith('#events'), 'COMMAND 切页同步地址 hash');
    check((await page.locator('h1').first().innerText()).includes('发现'), '低压力活动发现页加载');
    check(await page.locator('[data-action="interest"]').count() === 3, '全部活动卡提供有点兴趣入口');
    check(await page.locator('[data-action="companion"]').count() === 3, '全部活动卡提供想找同行入口');
    check((await page.locator('.low-pressure-note').innerText()).includes('不会占用活动名额'), '活动页明确低承诺动作不占名额');
    check(await page.locator('.events-screen .screen-bg').count() === 0, '活动页已移除干扰内容的视频背景');
    check((await page.locator('.events-screen').evaluate(el => getComputedStyle(el).backgroundImage)).includes('mission-city.webp'), '活动页使用任务城市 P5 背景');
    check(await page.locator('.mission-card').count() === 3, '活动与成员聚会同时呈现');    check(await page.locator('.event-club-filter').count() === 1, '活动页提供社团活动分类组件');
    check(await page.locator('[data-action=\"event-club-filter\"]').count() >= 3, '活动页提供全部社团、已加入社团和其他公开活动选项');
    check(await page.locator('.mission-card .event-club-label').count() === 3, '活动卡明确显示所属社团');
    await page.locator('[data-action=\"event-club-filter\"][data-id=\"g1\"]').click();
    check(await page.locator('.mission-card').count() === 1, '按已加入社团分类后只显示该社团活动');
    check((await page.locator('.mission-card').first().innerText()).includes('放映室常驻居民'), '社团分类结果保留所属社团名称');
    await page.locator('[data-action=\"event-club-filter\"][data-id=\"other\"]').click();
    check(await page.locator('.mission-card').count() === 2, '其他公开活动分类不会混入已加入社团活动');
    await page.locator('[data-action=\"event-club-filter\"][data-id=\"all\"]').click();
    await page.screenshot({ path: path.join(__dirname, 'low-pressure-events-desktop.png'), fullPage: false });
    const thresholdCard = page.locator('.mission-card').filter({ hasText: '随手画画 · 原创角色工坊' });
    check((await thresholdCard.locator('.formation-block').innerText()).includes('等待成团') && (await thresholdCard.locator('.formation-block').innerText()).includes('5 / 6'), '活动卡结构化显示等待成团 5/6');
    await thresholdCard.locator('[data-action="interest"]').click();
    await thresholdCard.locator('[data-action="companion"]').click();
    check((await thresholdCard.locator('.formation-block').innerText()).includes('5 / 6'), '兴趣与同行需求不会改变成团人数');
    await thresholdCard.locator('[data-action="event"]').click();
    check((await page.locator('.social-preview').innerText()).includes('图书馆东门长椅（示例）'), '活动预览展示同行集合点');
    check((await page.locator('#dialog .formation-block').first().innerText()).includes('等待成团'), '活动详情展示等待成团状态');
    await page.screenshot({ path: path.join(__dirname, 'formation-event-desktop.png'), fullPage: false });
    await page.locator('[data-action="register"][data-id="e3"]').click();
    check((await page.locator('#dialog .formation-block').first().innerText()).includes('已成团') && (await page.locator('#dialog .formation-block').first().innerText()).includes('6 / 6'), '报名达到门槛后活动切换为已成团');
    check((await page.locator('#action-feedback').innerText()).includes('最低人数已达成'), '达到最低人数时提供明确成功反馈');
    await page.waitForFunction(() => !document.querySelector('#action-feedback').matches(':popover-open'), null, { timeout: 4500 });
    await page.locator('[data-action="cancel"][data-id="e3"]').click();
    await page.locator('#dialog [data-action="interest"][data-id="e3"]').click();
    await page.locator('#dialog [data-action="companion"][data-id="e3"]').click();
    await page.getByRole('button', { name: '关闭简报', exact: true }).click();
    await page.locator('[data-action="interest"][data-id="e1"]').click();
    check(await page.locator('[data-action="interest"][data-id="e1"]').getAttribute('aria-pressed') === 'true', '有点兴趣可独立记录且保持可撤销状态');
    await page.locator('[data-action="companion"][data-id="e1"]').click();
    check(await page.locator('[data-action="companion"][data-id="e1"]').getAttribute('aria-pressed') === 'true', '想找同行可独立记录且不直接报名');

    await page.locator('[data-action="event"][data-id="e1"]').click();
    const previewText = await page.locator('.social-preview').innerText();
    check(!previewText.includes('社交强度') && !previewText.includes('交流程度'), '活动详情不再展示社交强度填写语义');
    check(!previewText.includes('中途离开'), '活动详情不再展示中途离开填写语义');
    check(await page.locator('.social-preview').evaluate(el => {
      const parse = value => (value.match(/[\d.]+/g) || []).slice(0, 3).map(Number);
      const luminance = value => { const rgb = parse(value).map(channel => { const c = channel / 255; return c <= .03928 ? c / 12.92 : ((c + .055) / 1.055) ** 2.4; }); return .2126 * rgb[0] + .7152 * rgb[1] + .0722 * rgb[2]; };
      const style = getComputedStyle(el); const foreground = luminance(style.color); const background = luminance(style.backgroundColor); const ratio = (Math.max(foreground, background) + .05) / (Math.min(foreground, background) + .05);
      return ratio >= 4.5;
    }), '桌面活动社交预览文字对比度至少达到 4.5:1');
    await page.screenshot({ path: path.join(__dirname, 'low-pressure-preview-desktop.png'), fullPage: false });
    await page.locator('[data-action="register"][data-id="e1"]').click();
    check((await page.locator('#dialog-body').innerText()).includes('你的状态：已确认'), '报名成功并明确显示已确认');
    check(await page.locator('#action-feedback').evaluate(el => el.matches(':popover-open') && el.classList.contains('show')), '报名角色反馈显示在模态层之上');
    check((await page.locator('#action-feedback').innerText()).includes('MISSION ACCEPTED'), '报名角色反馈显示 MISSION ACCEPTED');
    check(await page.locator('#action-feedback .feedback-character').evaluate(image => image.complete && image.naturalWidth > 0), '报名角色反馈图片加载成功');
    check(!await page.locator('#toast').evaluate(el => el.classList.contains('show')), '关键角色反馈不会叠加重复状态通知');
    await page.waitForTimeout(450);
    await page.screenshot({ path: path.join(__dirname, 'feedback-signup.png') });
    await page.waitForFunction(() => !document.querySelector('#action-feedback').matches(':popover-open'), null, { timeout: 4500 });
    await page.getByRole('button', { name: '行动岗位', exact: true }).click();
    await page.locator('[data-action="claim-role"]').first().click();
    check(await page.getByRole('button', { name: '已认领', exact: true }).count() === 1, '活动岗位可独立认领');
    await page.screenshot({ path: path.join(__dirname, 'mission-detail.png') });
    await page.locator('[data-action="cancel"][data-id="e1"]').click();
    check(await page.locator('#toast').getAttribute('data-status') === 'warning' && (await page.locator('#toast').innerText()).includes('WARNING'), '取消报名使用 WARNING 统一状态');
    { const detail = await page.locator('#dialog-body').innerText(); check(detail.includes('18') && detail.includes('/ 30'), '取消报名释放确认名额'); }
    await page.locator('[data-action="close"]').last().click();

    await page.locator('[data-action="event"][data-id="e2"]').click();
    await page.locator('[data-action="register"][data-id="e2"]').click();
    check((await page.locator('#dialog-body').innerText()).includes('你的状态：候补'), '满额活动进入候补');
    { const detail = await page.locator('#dialog-body').innerText(); check(detail.includes('08') && detail.includes('/ 08'), '候补不增加确认人数'); }
    await page.locator('[data-action="close"]').last().click();

    await page.getByRole('button', { name: /我的活动/ }).click();
    check(await page.locator('.mission-card').count() === 2, '我的活动同时汇总报名与同行需求');
    check(await page.locator('[data-action="filter"][data-id="我的活动"]').getAttribute('aria-pressed') === 'true' && await page.locator('[data-action="filter"][data-id="全部"]').getAttribute('aria-pressed') === 'false', '活动筛选选中态使用 aria-pressed 且不等同于禁用');
    await page.getByRole('button', { name: '全部', exact: true }).click();
    await page.getByLabel('搜索活动').fill('原创角色');
    check(await page.locator('.mission-card').count() === 1, '活动搜索即时过滤');
    await page.locator('[data-action="event"][data-id="e3"]').click();
    await page.locator('[data-action="register"][data-id="e3"]').click();
    await page.getByRole('button', { name: '签到核验', exact: true }).click();
    await page.locator('[data-action="checkin"][data-id="e3"]').click();
    check((await page.locator('#dialog-body').innerText()).includes('签到已完成'), '报名确认后可完成独立签到核验');
    check((await page.locator('#action-feedback').innerText()).includes('TASK COMPLETE'), '签到完成触发 TASK COMPLETE 角色反馈');
    await page.waitForFunction(() => !document.querySelector('#action-feedback').matches(':popover-open'), null, { timeout: 4500 });
    await page.locator('[data-action="close"]').last().click();

    await page.getByLabel('搜索活动').fill('不存在的行动目标');
    check(await page.locator('.p5-empty-state').count() === 1, '活动无结果时显示角色空状态');
    check(await page.locator('.p5-empty-state img').evaluate(image => image.complete && image.naturalWidth > 0), '活动空状态角色图片加载成功');
    await page.screenshot({ path: path.join(__dirname, 'empty-state.png') });
    await page.getByLabel('搜索活动').fill('');
    await page.locator('[data-action="event"][data-id="e1"]').click();
    await page.getByRole('button', { name: '活动回顾', exact: true }).click();
    await page.getByRole('button', { name: '创建活动回顾', exact: true }).click();
    check(await page.locator('#event-review-form').count() === 1, '活动回顾编辑器可从任务简报进入');
    await page.locator('#event-review-form [name="title"]').fill('a');
    await page.locator('#event-review-form [name="summary"]').fill('a');
    await page.locator('#event-review-form [name="highlights"]').fill('a');
    await page.locator('#event-review-form [name="suggestion"]').fill('a');
    await page.getByRole('button', { name: '保存草稿', exact: true }).click();
    check((await page.locator('#form-error').innerText()).includes('完整填写'), '自定义表单错误持续显示可读原因');
    check(await page.locator('#event-review-form [name="title"]').getAttribute('aria-invalid') === 'true' && (await page.locator('#event-review-form [name="title"]').getAttribute('aria-describedby') || '').includes('form-error'), '表单错误同步 aria-invalid 与 aria-describedby');
    check(await page.locator('#event-review-form [name="title"]').evaluate(el => document.activeElement === el), '表单校验失败后焦点回到首个字段');
    await page.locator('#event-review-form [name="title"]').fill('第一次夜间行动 <测试>');
    await page.locator('#event-review-form [name="summary"]').fill('成员完成了主题拍摄、分组交流和现场复盘，整体流程顺利。');
    await page.locator('#event-review-form [name="highlights"]').fill('新人主动承担现场引导，作品展示区互动热烈。');
    await page.locator('#event-review-form [name="suggestion"]').fill('下次增加设备检查清单，并预留更长的自由交流时间。');
    await page.getByRole('button', { name: '保存草稿', exact: true }).click();
    check((await page.locator('.review-published').innerText()).includes('草稿'), '活动回顾可保存为不公开草稿');
    await page.getByRole('button', { name: '继续编辑', exact: true }).click();
    check(await page.locator('#event-review-form [name="title"]').inputValue() === '第一次夜间行动 <测试>', '活动回顾草稿可恢复继续编辑');
    await page.locator('#event-review-form [name="media"]').fill('成员合照 3 张与插画 5 幅');
    check(await page.locator('#event-review-form').evaluate((form) => form.getBoundingClientRect().left - document.querySelector('#dialog').getBoundingClientRect().left >= 24), '活动回顾表单与斜切边缘保持可读留白');
    await page.screenshot({ path: path.join(__dirname, 'review-editor.png'), fullPage: false });
    await page.getByRole('button', { name: /提交发布审核/ }).click();
    check((await page.locator('#form-error').innerText()).includes('授权'), '带作品说明的活动回顾必须确认展示授权');
    await page.locator('#event-review-form [name="consent"]').check();
    await page.getByRole('button', { name: /提交发布审核/ }).click();
    check((await page.locator('.review-published').innerText()).includes('待发布审核'), '活动回顾提交后进入发布审核状态');
    await page.getByRole('button', { name: '打开阅读窗口', exact: true }).click();
    check(parseFloat(await page.locator('.reading-sheet section p').first().evaluate(el => getComputedStyle(el).fontSize)) >= 16, '活动回顾阅读窗口使用至少 16px 正文字号');
    check(await page.locator('.reading-sheet script').count() === 0 && (await page.locator('#dialog-title').innerText()).includes('<测试>'), '活动回顾用户文本经过安全转义');
    await page.locator('[data-action="close"]').last().click();
    await switchPage(page, 'community');
    check((await page.locator('.community-screen').evaluate(el => getComputedStyle(el).backgroundImage)).includes('bonds-collage.webp'), '同好页使用羁绊角色拼贴背景');
    check(await page.getByRole('button', { name: '群文件说明', exact: true }).count() === 1, '同好页提供轻量群文件说明入口');
    check(await page.locator('.bond-card').count() === 3, '内部小组列表加载');
    check(await page.locator('.game-chip').count() === 6, '首批六款游戏入口齐全');
    await page.locator('[data-action="public-club"]').click();
    check(await page.locator('.public-club-dialog').count() === 1, '公开社团主页弹窗加载');
    check((await page.locator('.public-club-hero').innerText()).includes('演示'), '公开主页明确标注演示');
    check((await page.locator('.public-club-rules').innerText()).includes('示例数据不代表真实通知或权限'), '公开主页展示演示边界');
    check(await page.locator('.public-club-events button').count() >= 1, '公开主页展示近期活动入口');
    await page.locator('.public-club-events button').first().click();
    check(await page.locator('.mission-dialog').count() === 1, '公开主页活动入口可进入活动详情');
    await page.locator('[data-action="close"]').last().click();
    await page.locator('[data-action="public-club"]').click();
    await page.screenshot({ path: path.join(__dirname, 'public-club-desktop.png'), fullPage: false });
    await page.locator('[data-action="close"]').last().click();    await page.locator('[data-action="group"][data-id="g2"]').click();
    await page.locator('[data-action="join"][data-id="g2"]').click();
    check((await page.locator('#action-feedback').innerText()).includes('BOND FORMED'), '加入小组触发 BOND FORMED 角色反馈');
    await page.waitForFunction(() => !document.querySelector('#action-feedback').matches(':popover-open'), null, { timeout: 4500 });
    await page.locator('[data-action="close"]').last().click();
    await page.locator('[data-action="group"][data-id="g1"]').click();
    await page.getByRole('button', { name: '共享文件', exact: true }).click();
    check(await page.locator('.file-board article').count() === 2, '小组共享文件分区加载');
    { const filesText = await page.locator('.file-board').innerText(); check(filesText.includes('1.8 MB') && filesText.includes('栗子'), '共享文件保留文件大小与上传成员'); }
    { const filesText = await page.locator('.file-board').innerText(); check(!filesText.includes('来源') && !filesText.includes('授权') && !filesText.includes('审核状态'), '共享文件不展示来源、授权或审核状态'); }
    check((await page.locator('[data-action="file-upload-demo"]').innerText()).includes('LOCKED'), '共享文件上传入口明确标记 LOCKED');
    await page.locator('[data-action="file-upload-demo"]').click();
    check((await page.locator('#dialog-body').innerText()).includes('没有文件选择器、网络传输、对象存储、安全扫描、下载链接或持久化'), '上传流程外壳明确说明没有真实后端能力');
    check(await page.locator('#toast').getAttribute('data-status') === 'locked' && (await page.locator('#toast').innerText()).includes('LOCKED'), '未接后端的上传入口使用 LOCKED 统一状态');
    check(await page.locator('#dialog input[type="file"]').count() === 0, '上传流程外壳不会打开真实文件选择器');
    check(await page.locator('.upload-demo-steps li').count() === 6, '上传流程外壳展示六个协议阶段');
    check(await page.locator('[data-upload-stage="rules"]').count() === 1, '上传流程从规则与配额说明开始');
    await page.getByRole('button', { name: '建立演示上传任务', exact: true }).click();
    check(await page.locator('[data-upload-stage="queued"] .status-chip.pending').count() === 1, '虚构上传任务进入 PENDING 等待状态');
    check((await page.locator('.upload-fake-file').innerText()).includes('未读取本机文件'), '等待状态明确使用未读取本机文件的虚构样本');
    await page.getByRole('button', { name: '模拟进入传输进度', exact: true }).click();
    check(await page.locator('[role="progressbar"]').getAttribute('aria-valuenow') === '68', '上传进度阶段提供可访问的演示进度');
    check((await page.locator('.upload-progress').innerText()).includes('已传输 0 B'), '演示进度明确没有传输真实字节');
    await page.getByRole('button', { name: '模拟一次通道中断', exact: true }).click();
    check(await page.locator('[data-upload-stage="failed"] .status-chip.failed').count() === 1, '上传流程覆盖 FAILED 中断状态');
    check(await page.locator('#toast').getAttribute('data-status') === 'failed', '上传演示失败使用 FAILED 统一状态');
    await page.getByRole('button', { name: '模拟重试并查看扫描', exact: true }).click();
    check((await page.locator('[data-upload-stage="scan"]').innerText()).includes('当前并未执行真实安全扫描'), '安全扫描阶段诚实说明扫描尚未接入');
    check(await page.locator('.upload-scan-list li').count() === 4, '安全扫描协议列出类型、恶意内容、权限配额与指纹检查');
    await page.screenshot({ path: path.join(__dirname, 'upload-flow-desktop.png') });
    await page.getByRole('button', { name: '查看完成状态预览', exact: true }).click();
    check(await page.locator('[data-upload-stage="complete"] .status-chip.success').count() === 1, '上传流程提供 SUCCESS 完成状态预览');
    check((await page.locator('.upload-complete-stamp').innerText()).includes('没有新增共享文件'), '完成预览不会伪造已保存文件');
    check(await page.locator('#toast').getAttribute('data-status') === 'success', '完成预览使用 SUCCESS 统一状态');
    await page.getByRole('button', { name: '返回共享文件', exact: true }).click();
    check(await page.locator('.file-board article').count() === 2, '完成上传流程预览后共享文件数量保持不变');    await page.locator('[data-action="save-file"]').first().click();
    check(await page.locator('[data-action="save-file"]').first().getAttribute('aria-pressed') === 'true', '小组资源可加入演示收藏');
    check(!await page.locator('[data-action="save-file"]').first().isDisabled(), '收藏选中态保持可取消，不误用 disabled');
    check(await page.locator('#toast').getAttribute('data-status') === 'success' && (await page.locator('#toast').innerText()).includes('SUCCESS'), '收藏操作使用 SUCCESS 统一状态');
    await page.screenshot({ path: path.join(__dirname, 'group-hub.png') });
    await page.getByRole('button', { name: '小组动态', exact: true }).click();
    await page.getByRole('button', { name: '发布动态', exact: true }).click();
    check(await page.locator('#group-post-form').count() === 1, '小组动态编辑器可从内部频道进入');
    await page.locator('#group-post-form [name="title"]').fill('周末补番计划 <安全测试>');
    await page.locator('#group-post-form [name="text"]').fill('本周准备一起观看三集动画，之后讨论角色塑造与分镜。<script>window.bad=true</script> 请自带饮料，并避免提前剧透。');
    await page.locator('#group-post-form [name="type"]').selectOption('活动情报');
    await page.locator('#group-post-form [name="visibility"]').selectOption('全社团可见');
    await page.locator('#group-post-form [name="spoiler"]').check();
    await page.getByRole('button', { name: '保存草稿', exact: true }).click();
    check(await page.getByRole('button', { name: '继续草稿', exact: true }).count() === 1, '小组动态可保存草稿且不公开');
    await page.getByRole('button', { name: '继续草稿', exact: true }).click();
    check((await page.locator('#group-post-form [name="text"]').inputValue()).includes('角色塑造与分镜'), '小组动态草稿可恢复继续编辑');
    await page.getByRole('button', { name: /发布动态/ }).click();
    const newestPost = page.locator('.post-list article').first();
    check((await newestPost.innerText()).includes('周末补番计划 <安全测试>'), '发布的小组动态出现在频道顶部');
    check(await page.locator('#toast').getAttribute('data-status') === 'new' && (await page.locator('#toast').innerText()).includes('NEW'), '新动态发布使用 NEW 统一状态');
    check(await newestPost.locator('script').count() === 0 && await page.evaluate(() => !window.bad), '小组动态标题与正文经过安全转义');
    check((await newestPost.innerText()).includes('SPOILER') && (await newestPost.innerText()).includes('全社团可见'), '小组动态保留剧透与可见范围标记');
    await newestPost.getByRole('button', { name: /展开阅读/ }).click();
    check(await page.locator('.reading-dialog').count() === 1, '较长小组动态可打开独立阅读窗口');
    check(parseFloat(await page.locator('.post-reading>section p').evaluate(el => getComputedStyle(el).fontSize)) >= 16, '小组动态阅读窗口使用至少 16px 正文字号');
    await page.getByRole('button', { name: '反馈内容', exact: true }).click();
    await page.locator('#post-report-form [name="reason"]').selectOption('剧透未标记');
    await page.locator('#post-report-form [name="note"]').fill('请管理员核验剧透提示是否足够醒目。');
    await page.locator('#post-report-form button[type="submit"]').click();
    const reportedPost = page.locator('.post-list article').first();
    const reportedButton = reportedPost.locator('[data-action="report-post"]');
    check(await reportedButton.isDisabled() && await reportedButton.getAttribute('data-state') === 'PENDING', '内容反馈提交后进入明确 PENDING 禁用状态');
    check((await reportedPost.locator('.p5-inline-status.pending').innerText()).includes('反馈等待演示审核'), '内容反馈旁显示持续可见的等待审核说明');
    check(await page.locator('#toast').getAttribute('data-status') === 'pending' && (await page.locator('#toast').innerText()).includes('PENDING'), '内容反馈使用 PENDING 统一状态');
    check((await reportedPost.innerText()).includes('周末补番计划'), '内容反馈不会无提示删除原动态');
    await page.screenshot({ path: path.join(require('node:os').tmpdir(), 'p5-state-system-desktop.png'), fullPage: false });
    await page.locator('[data-action="close"]').last().click();
    await page.locator('.game-chip').first().click();
    check(await page.locator('.game-sheet-head').count() === 1, '游戏专区详情加载');
    check(await page.locator('.game-tabs button').count() === 5, '游戏专区五个分区齐全');
    await page.locator('[data-action="game-follow"]').click();
    check((await page.locator('#dialog-body').innerText()).includes('取消关注'), '游戏关注与报名状态独立');
    await page.getByRole('button', { name: '我的名片', exact: true }).click();
    await page.locator('[data-action="edit-game-card"]').click();
    await page.locator('#game-card-form input[name="alias"]').fill('夜航 <测试>');
    await page.locator('#game-card-form input[name="server"]').fill('仅社团可见');
    await page.locator('#game-card-form input[name="time"]').fill('周五晚上');
    await page.locator('#game-card-form button[type="submit"]').click();
    check((await page.locator('.player-card').innerText()).includes('夜航 <测试>'), '游戏名片保存且用户文本安全渲染');
    await page.getByRole('button', { name: '寻找队友', exact: true }).click();
    await page.locator('[data-action="join-squad"]').first().click();
    check(await page.locator('[data-action="join-squad"]').first().getAttribute('aria-pressed') === 'true', '组队意向可发送和独立记录');
    await page.getByRole('button', { name: '赛季记录', exact: true }).click();
    check((await page.locator('.season-sheet').innerText()).includes('NO API'), '赛季记录明确未连接游戏接口');
    await page.getByRole('button', { name: '社团榜单', exact: true }).click();
    check((await page.locator('.ranking-empty').innerText()).includes('尚未启用'), '社团榜单使用诚实空状态');
    check(await page.locator('.ranking-empty img').evaluate(image => image.complete && image.naturalWidth > 0), '榜单空状态角色图片加载成功');
    await page.locator('.game-tabs [data-id="honor:overview"]').click();
    await page.locator('[data-action="game-meet"]').first().click();
    check(await page.locator('#gathering-form input[name="title"]').inputValue() === '王者荣耀组队行动', '游戏专区可带入开黑小聚表单');
    await page.locator('[data-action="close"]').last().click();
    await page.locator('.game-chip').first().click();
    await page.screenshot({ path: path.join(__dirname, 'game-zone.png') });
    await page.locator('[data-action="close"]').last().click();

    for (let gameIndex = 0; gameIndex < 6; gameIndex += 1) {
      const gameChip = page.locator('.game-chip').nth(gameIndex);
      const gameName = (await gameChip.locator('b').innerText()).trim();
      await gameChip.click();
      check(await page.locator('.game-sheet-head').count() === 1, `${gameName} 游戏专区可进入`);
      await page.locator('[data-action="game-meet"]').first().click();
      check((await page.locator('.gathering-context').innerText()).includes(`${gameName} · 组队小聚`), `${gameName} 小聚上下文来源正确`);
      check(await page.locator('#gathering-form input[name="title"]').inputValue() === `${gameName}组队行动`, `${gameName} 标题预填正确`);
      check(await page.locator('#gathering-form input[name="place"]').inputValue() === '线上集合（社团内部）', `${gameName} 地点预填正确`);
      await page.locator('#gathering-form input[name="title"]').fill(`${gameName}自定义行动`);
      await page.locator('#gathering-form input[name="place"]').fill('社团线上房间（示例）');
      check(await page.locator('#gathering-form input[name="title"]').inputValue() === `${gameName}自定义行动` && await page.locator('#gathering-form input[name="place"]').inputValue() === '社团线上房间（示例）', `${gameName} 预填字段可编辑`);
      await page.locator('[data-action="close"]').last().click();
    }
    await page.locator('[data-action="places"]').click();
    check(await page.locator('.campus-card').count() === 4, '校园地点作战手册加载');
    await page.locator('[data-action="favorite-place"][data-id="c1"]').click();
    check(await page.locator('[data-action="favorite-place"][data-id="c1"]').getAttribute('aria-pressed') === 'true', '校园地点可加入收藏');
    await page.getByRole('button', { name: /周边美食/ }).click();
    check(await page.locator('.campus-card').count() === 4, '周边美食分区加载');
    await page.getByRole('button', { name: /社员推荐/ }).click();
    check(await page.locator('.campus-notes article').count() === 3, '社员推荐情报板加载');
    await page.getByRole('button', { name: /我的收藏/ }).click();
    check(await page.locator('.campus-card').count() === 1, '校园收藏分区保持独立状态');
    await page.getByRole('button', { name: '校园地点', exact: true }).click();
    await page.locator('[data-action="campus-meet"][data-id="c1"]').click();
    check(await page.locator('#gathering-form input[name="place"]').inputValue() === '活动中心 203', '地点可带入成员小聚表单');
    await page.locator('[data-action="close"]').last().click();
    await page.locator('[data-action="places"]').click();
    await page.screenshot({ path: path.join(__dirname, 'campus-guide.png') });
    await page.locator('[data-action="close"]').last().click();

    await page.locator('[data-action="create-group"]').click();
    check(await page.locator('#group-form input[name="name"]').evaluate(el => el.closest('label')?.innerText.includes('小组名称')) && await page.locator('#group-form textarea[name="desc"]').evaluate(el => el.closest('label')?.innerText.includes('小组介绍')), '动态表单控件均有可见标签');
    await page.locator('#group-form input[name="name"]').fill('测试 <绘画> 组');
    await page.locator('#group-form textarea[name="desc"]').fill('一起创作的演示小组');
    await page.locator('#group-form button[type="submit"]').click();
    check(await page.getByRole('heading', { name: '测试 <绘画> 组' }).count() === 1, '建组成功且用户文本安全渲染');

    await switchPage(page, 'hub');
    await page.locator('[data-action="gathering"]').first().click();
    check(await page.locator('#gathering-form [name="minParticipants"]').count() === 1 && await page.locator('#gathering-form [name="socialLevel"]').count() === 0 && await page.locator('#gathering-form [name="canLeave"]').count() === 0 && await page.locator('#gathering-form [name="meetPoint"]').count() === 1, '成员小聚表单包含成团人数与集合点且已移除社交强度字段');
    check(await page.locator('#dialog .dialog-close').evaluate((button, dialog) => { const d = dialog.getBoundingClientRect(); const c = button.getBoundingClientRect(); return c.right <= d.right && c.left >= d.left && c.top >= d.top && c.left > d.left + d.width / 2; }, await page.locator('#dialog').elementHandle()), '桌面次级窗口关闭按钮位于弹窗右上角');
    const gatheringTitleStyle = await page.locator('#gathering-form input[name="title"]').evaluate(el => { const style = getComputedStyle(el); return { color: style.color, caretColor: style.caretColor, backgroundColor: style.backgroundColor }; });
    check(gatheringTitleStyle.color !== gatheringTitleStyle.backgroundColor && gatheringTitleStyle.caretColor !== gatheringTitleStyle.backgroundColor, '成员小聚文本输入文字与光标颜色可见');
    await page.locator('#gathering-form input[name="title"]').fill('测试原创小聚');
    await page.locator('#gathering-form input[name="time"]').fill('2026-10-01T15:00');
    await page.locator('#gathering-form input[name="place"]').fill('虚构创作室');
    await page.locator('#gathering-form input[name="capacity"]').fill('6');
    await page.locator('#gathering-form input[name="minParticipants"]').fill('7');
    await page.locator('#gathering-form input[name="meetPoint"]').fill('虚构创作室门口');
    await page.locator('#gathering-form input[name="welcomeHost"]').fill('林同学（示例）');
    await page.locator('#gathering-form button[type="submit"]').click();
    check((await page.locator('#gathering-form .form-error').innerText()).includes('不能超过活动容量'), '成员小聚阻止最低成团人数高于容量');
    await page.locator('#gathering-form input[name="minParticipants"]').fill('2');
    await page.screenshot({ path: path.join(__dirname, 'formation-form-desktop.png'), fullPage: false });
    await page.locator('#gathering-form button[type="submit"]').click();
    await page.waitForTimeout(850);
    check(page.url().endsWith('#events'), '发布小聚后转到活动页');
    check(await page.locator('.created-event-receipt').count() === 1, '创建成功显示页面内结果回执');
    check((await page.locator('.created-event-receipt').innerText()).includes('测试原创小聚') && (await page.locator('.created-event-receipt').innerText()).includes('发起者已计入 1/6'), '创建回执展示标题与人数');
    await page.locator('.created-event-receipt [data-action="event"]').click();
    check((await page.locator('#dialog-body').innerText()).includes('测试原创小聚'), '创建回执可查看活动详情');
    await page.locator('[data-action="close"]').last().click();
    await page.locator('[data-action="gathering"]').last().click();
    await page.locator('#gathering-form input[name="title"]').fill('第二场测试原创小聚');
    await page.locator('#gathering-form input[name="time"]').fill('2026-10-02T15:00');
    await page.locator('#gathering-form input[name="place"]').fill('第二处虚构创作室');
    await page.locator('#gathering-form input[name="capacity"]').fill('5');
    await page.locator('#gathering-form input[name="minParticipants"]').fill('2');
    await page.locator('#gathering-form input[name="meetPoint"]').fill('第二处集合点（示例）');
    await page.locator('#gathering-form input[name="welcomeHost"]').fill('小林（示例）');
    await page.locator('#gathering-form button[type="submit"]').click();
    await page.waitForTimeout(850);
    const latestReceiptText = await page.locator('.created-event-receipt').innerText();
    check(await page.locator('.created-event-receipt').count() === 1 && latestReceiptText.includes('第二场测试原创小聚') && !latestReceiptText.includes('发起者已计入 1/6'), '再次创建替换旧回执');
    const firstCreatedCard = page.getByRole('heading', { name: '测试原创小聚', exact: true }).locator('..');
    check(await firstCreatedCard.count() === 1, '成员可发起聚会');
    await firstCreatedCard.locator('[data-action="event"]').click();
    const newEventDetail = await page.locator('#dialog-body').innerText();
    check(newEventDetail.includes('01') && newEventDetail.includes('/ 06'), '聚会发起者计入人数');
    check(newEventDetail.includes('等待成团') && newEventDetail.includes('1 / 2'), '新小聚以 1/2 等待成团状态发布');
    check(newEventDetail.includes('虚构创作室门口') && newEventDetail.includes('林同学（示例）'), '新小聚详情展示同行集合点与迎新联系人');
    check(newEventDetail.includes('报名截止 10.01 14:00'), '新聚会截止时间正确');
    await page.locator('[data-action="close"]').last().click();
    await page.locator('[data-action="quick-menu"]').first().click();
    await page.locator('[data-action="goto"][data-id="me"]').click();
    await page.waitForTimeout(850);
    check(page.url().endsWith('#me'), '快捷 COMMAND 可在弹窗内切页');
    check(!await page.locator('#dialog').evaluate(el => el.open), '弹窗内跳页会先关闭弹窗');
    check(await page.locator('.profile-card').count() === 1, '成员档案页加载');
    check((await page.locator('.theme-contract').innerText()).includes('P5 风格') && (await page.locator('.theme-contract').innerText()).includes('OTHER WORKS / RESERVED'), '我的页面展示当前主题与未来主题预留契约');
    check(await page.locator('.status-protocol .status-chip').count() === 6, '统一状态协议展示六种核心语义');
    await page.locator('#motion').check();
    check(await page.locator('body').evaluate(el => el.classList.contains('reduced-motion')), '减少动效开关生效');

    await page.goBack();
    await page.waitForTimeout(850);
    check(page.url().endsWith('#events'), '浏览器后退可恢复上一页');
    check(await page.locator('.events-screen').count() === 1, '后退后页面内容同步');
    check(await page.locator('#page-intro').evaluate(el => el.classList.contains('show') && getComputedStyle(el.querySelector('.page-intro-speedlines')).display === 'none'), '减少动效时页面进入提示降级为无速度线静态淡入');

    await page.keyboard.press('KeyM');
    check(await page.locator('#dialog').evaluate(el => el.open), 'M 键打开快捷 COMMAND');
    await page.keyboard.press('Escape');
    check(!await page.locator('#dialog').evaluate(el => el.open), 'Escape 关闭弹窗');

    await page.locator('[data-route="me"]').first().click();
    await page.waitForTimeout(850);
    await page.locator('[data-action="leader-console"]').click();
    await page.getByRole('button', { name: '权限与审核', exact: true }).click();
    check(await page.locator('.review-card').filter({ hasText: '第一次夜间行动 <测试>' }).count() === 1, '活动回顾提交后进入社长内容审核队列');
    check(await page.locator('.review-card').filter({ hasText: '周末补番计划 <安全测试>' }).count() === 1, '小组动态反馈进入社长内容审核队列');
    await page.locator('[data-action="review-decision"][data-id="er-e1:approve"]').click();
    check((await page.locator('.review-card').filter({ hasText: '第一次夜间行动 <测试>' }).innerText()).includes('审核通过'), '社长审核活动回顾后记录审核结果');
    await page.locator('[data-action="close"]').last().click();
    await page.locator('[data-route="events"]').first().click();
    await page.waitForTimeout(850);
    await page.locator('[data-action="event"][data-id="e1"]').click();
    await page.getByRole('button', { name: '活动回顾', exact: true }).click();
    check((await page.locator('.review-published').innerText()).includes('已发布'), '活动回顾通过审核后同步为已发布');
    await page.locator('[data-action="close"]').last().click();
    await page.reload();
    await page.waitForTimeout(850);
    check(await page.locator('.created-event-receipt').count() === 0, '刷新后创建回执清除');

    const leader = await open({ width: 1440, height: 1080 }, '#me');
    check((await leader.locator('.profile-card').innerText()).includes('无管理权限'), '普通成员身份仍明确无管理权限');
    check(await leader.locator('[data-action="leader-console"]').count() === 1, '我的页面提供社长工作台演示入口');
    await leader.locator('[data-action="leader-console"]').click();
    check(await leader.locator('#dialog').evaluate(el => el.classList.contains('leader-dialog')), '社长工作台使用独立 P5 指挥室形态');
    check(await leader.locator('.leader-tabs button').count() === 6, '社长工作台六个分区齐全');
    check((await leader.locator('.leader-preview-warning').innerText()).includes('不代表'), '管理预览不会静默授予权限');
    await leader.screenshot({ path: path.join(__dirname, 'leader-console.png'), fullPage: false });

    await leader.getByRole('button', { name: '发布活动', exact: true }).click();
    check(await leader.locator('#official-event-form [name="formationMode"]').count() === 1 && await leader.locator('#official-event-form [name="meetPoint"]').count() === 1, '正式活动表单复用低压力活动模板');
    check(await leader.locator('#official-event-form [name="socialLevel"]').count() === 0, '正式活动表单已移除社交强度');
    check(await leader.locator('#official-event-form [name="canLeave"]').count() === 0, '正式活动表单已移除中途离开');
    check(await leader.locator('#official-event-form [name="minParticipants"]').isDisabled(), '正式活动默认立即开放时停用最低成团人数');
    await leader.locator('#official-event-form [name="formationMode"]').selectOption('threshold');
    check(!await leader.locator('#official-event-form [name="minParticipants"]').isDisabled(), '正式活动可切换为达到人数再成团');
    await leader.locator('#official-event-form [name="minParticipants"]').fill('8');
    await leader.locator('#official-event-form [name="title"]').fill('十月新番联合放映');
    check(await leader.locator('#official-event-form [name="title"]').inputValue() === '十月新番联合放映', '正式活动标题文本输入可以写入');
    await leader.locator('#official-event-form [name="time"]').fill('2026-10-16T18:30');
    await leader.locator('#official-event-form [name="cutoff"]').fill('2026-10-15T22:00');
    await leader.locator('#official-event-form [name="place"]').fill('活动中心 301（示例）');
    await leader.locator('#official-event-form [name="meetPoint"]').fill('活动中心一楼大厅（示例）');
    await leader.locator('#official-event-form [name="welcomeHost"]').fill('活动组阿泽（示例）');
    await leader.locator('#official-event-form [name="capacity"]').fill('24');
    await leader.locator('#official-event-form [name="desc"]').fill('面向全体成员的新番联合放映与交流活动。');
    await leader.locator('#official-event-form [name="requirements"]').fill('提前十分钟到场；剧透内容需提醒');
    await leader.locator('#official-event-form [name="roles"]').fill('签到；设备；现场引导');
    await leader.locator('#official-event-form button[type="submit"]').click();
    await leader.waitForTimeout(850);
    check(leader.url().endsWith('#events'), '发布正式活动后进入活动页');
    check(await leader.locator('.mission-card').count() === 4, '正式活动发布进入现有活动列表');
    const officialCard = leader.locator('.mission-card').filter({ hasText: '十月新番联合放映' });
    check(await officialCard.count() === 1, '新正式活动标题正确呈现');
    check((await officialCard.innerText()).includes('0/24'), '社长不会被自动计入正式活动人数');
    check((await officialCard.locator('.formation-block').innerText()).includes('等待成团') && (await officialCard.locator('.formation-block').innerText()).includes('0 / 8'), '新正式活动显示 0/8 等待成团');

    await switchPage(leader, 'me');
    await leader.locator('[data-action="leader-console"]').click();
    await leader.getByRole('button', { name: '成员管理', exact: true }).click();
    check(await leader.locator('.application-card').count() === 3, '工作台加载三条入社申请');
    await leader.locator('[data-action="application-decision"][data-id$=":approve"]').first().click();
    check(await leader.locator('.application-card').count() === 2, '入社申请通过后从待处理列表移除');
    check(await leader.locator('#application-last-result[data-state="SUCCESS"]').count() === 1 && (await leader.locator('#application-last-result').innerText()).includes('最近处理'), '入社决定保留轻量完成回执，不只依赖 toast');
    await leader.locator('[data-member-role="m4"]').selectOption('小组组长');
    check((await leader.locator('.permission-note').innerText()).includes('不会自动获得'), '小组组长与社团管理员权限保持分离');
    check(await leader.locator('.member-row').filter({ has: leader.locator('[data-member-role="m4"]') }).locator('.member-operation-state[data-state="SUCCESS"]').count() === 1, '成员角色更新保留页面内完成态');
    while (await leader.locator('[data-action="application-decision"][data-id$=":reject"]').count()) await leader.locator('[data-action="application-decision"][data-id$=":reject"]').first().click();
    check(await leader.locator('#application-empty[data-state="SUCCESS"]').count() === 1 && (await leader.locator('#application-empty').innerText()).includes('所有入社申请已处理'), '入社申请清空后显示轻量完成空态');
    await leader.locator('#application-empty').scrollIntoViewIfNeeded();
    await leader.screenshot({ path: path.join(__dirname, 'management-states.png'), fullPage: false });
    await leader.locator('[data-action="member-danger"]').first().click();
    await leader.locator('[data-action="confirm-member-action"]').click();
    check(await leader.locator('#toast').getAttribute('data-status') === 'failed' && (await leader.locator('#toast').innerText()).includes('FAILED'), '高风险操作缺少原因时使用 FAILED 统一状态');
    await leader.locator('#danger-reason').fill('连续违反演示活动规则');
    await leader.locator('[data-action="confirm-member-action"]').click();
    check(await leader.locator('.member-operation-state[data-state="WARNING"]').count() === 1, '高风险成员操作完成后保留页面内警示回执');

    await leader.getByRole('button', { name: '公告', exact: true }).click();
    await leader.locator('#notice-form [name="title"]').fill('十月活动安全提醒');
    await leader.locator('#notice-form [name="content"]').fill('离校活动必须填写紧急联系人并遵守集合纪律。');
    await leader.locator('#notice-form [name="version"]').fill('v2');
    await leader.locator('#notice-form button[type="submit"]').click();
    check(await leader.locator('.notice-stats article').count() === 2, '新公告进入公告统计列表');
    const newNotice = leader.locator('.notice-stats article').first();
    check((await newNotice.innerText()).includes('0 已打开') && (await newNotice.innerText()).includes('0 已明确确认'), '公告打开与明确确认分开统计');
    await leader.locator('[data-action="close"]').last().click();
    await leader.locator('.mail').click();
    await leader.locator('[data-action="message-filter"][data-id="系统"]').click();
    check((await leader.locator('.message-card').first().innerText()).includes('十月活动安全提醒'), '社长发布的公告进入消息中心');
    await leader.locator('.message-card').first().locator('[data-action="message-detail"]').click();
    await leader.locator('[data-action="message-target"]').click();
    await leader.locator('[data-action="confirm-notice"]').click();
    await leader.locator('[data-action="leader-console"]').click();
    await leader.getByRole('button', { name: '公告', exact: true }).click();
    const confirmedNotice = await leader.locator('.notice-stats article').first().innerText();
    check(confirmedNotice.includes('1 已打开') && confirmedNotice.includes('1 已明确确认'), '新公告从消息跳转后打开与确认分别计数');

    await leader.getByRole('button', { name: '权限与审核', exact: true }).click();
    await leader.locator('[data-action="review-decision"][data-id="q1:approve"]').click();
    check((await leader.locator('.review-card').first().innerText()).includes('审核通过'), '内容审核动作被明确记录');
    check(await leader.locator('.review-card').first().locator('.review-result[data-state="SUCCESS"]').count() === 1, '审核完成态使用轻量状态组件持续呈现');

    await leader.getByRole('button', { name: '活动详情', exact: true }).click();
    await leader.getByRole('button', { name: /十月新番联合放映/ }).click();
    check(await leader.locator('#roster-empty[data-state="NOTICE"]').count() === 1, '无报名样本时使用轻量局部空态而非空白表格');
    await leader.locator('[data-action="leader-event"][data-id="e2"]').click();
    await leader.locator('[data-action="roster-action"][data-id="e2:r6:cancel"]').click();
    check((await leader.locator('.roster-summary').innerText()).includes('7'), '取消确认资格会释放活动容量');
    check(await leader.locator('.roster-result[data-state="WARNING"]').count() === 1, '取消资格后保留页面内警示回执');
    await leader.locator('[data-action="roster-action"][data-id="e2:r8:promote"]').click();
    check((await leader.locator('.roster-summary').innerText()).includes('8'), '释放容量后可递补候补成员');
    await leader.close();

    const mobile = await open({ width: 390, height: 844 }, '#hub');
    await mobile.locator('[data-action="gathering"]').first().click();
    check(await mobile.locator('#gathering-form [name="socialLevel"]').count() === 0, '成员小聚表单已移除社交强度');
    check(await mobile.locator('#gathering-form [name="canLeave"]').count() === 0, '成员小聚表单已移除中途离开');
    await mobile.locator('#gathering-form [name="title"]').fill('移动端输入验证标题');
    await mobile.locator('#gathering-form [name="time"]').fill('2026-10-03T15:00');
    await mobile.locator('#gathering-form [name="place"]').fill('移动端示例地点');
    await mobile.locator('#gathering-form [name="capacity"]').fill('4');
    await mobile.locator('#gathering-form [name="minParticipants"]').fill('2');
    await mobile.locator('#gathering-form [name="meetPoint"]').fill('移动端集合点（示例）');
    await mobile.locator('#gathering-form [name="welcomeHost"]').fill('移动端联系人（示例）');
    await mobile.screenshot({ path: path.join(__dirname, 'formation-form-mobile.png'), fullPage: false });
    check(await mobile.locator('#gathering-form').evaluate(el => el.scrollWidth <= innerWidth && el.getBoundingClientRect().width <= innerWidth), '移动端低压力活动表单不超出 390px 视口');
    check(await mobile.locator('#dialog .dialog-close').evaluate((button, dialog) => { const d = dialog.getBoundingClientRect(); const c = button.getBoundingClientRect(); return c.right <= d.right && c.left >= d.left && c.top >= d.top && c.left > d.left + d.width / 2; }, await mobile.locator('#dialog').elementHandle()), '移动端次级窗口关闭按钮位于弹窗右上角');
    check(await mobile.locator('#gathering-form [name="title"]').inputValue() === '移动端输入验证标题', '成员小聚文本输入可以写入');
    await mobile.locator('#gathering-form button[type="submit"]').click();
    await mobile.waitForTimeout(850);
    check(await mobile.locator('.created-event-receipt').count() === 1, '移动端创建成功显示结果回执');
    check(await mobile.locator('.created-event-receipt').evaluate(el => el.getBoundingClientRect().width <= innerWidth && el.scrollWidth <= innerWidth), '移动端创建回执不超出视口');
    await mobile.locator('.created-event-receipt [data-action="event"]').click();
    check((await mobile.locator('#dialog-body').innerText()).includes('移动端输入验证标题'), '移动端创建回执可查看活动详情');
    await mobile.locator('[data-action="close"]').last().click();
    await mobile.reload();
    await mobile.waitForTimeout(850);
    check(await mobile.locator('.created-event-receipt').count() === 0, '移动端刷新后创建回执清除');
    check(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '移动端据点无横向溢出');
    check(await mobile.locator('.command-nav').evaluate(el => getComputedStyle(el).position === 'fixed'), '移动端 COMMAND 导航固定可达');
    await switchPage(mobile, 'hub');
    await switchPage(mobile, 'events');
    check(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '移动端活动页无横向溢出');
    check((await mobile.locator('.events-screen').evaluate(el => getComputedStyle(el).backgroundImage)).includes('mission-city.webp'), '移动端活动背景正常加载');
    await mobile.screenshot({ path: path.join(__dirname, 'low-pressure-events-mobile.png'), fullPage: false });
    await mobile.locator('[data-action="event"][data-id="e3"]').click();
    check((await mobile.locator('#dialog .formation-block').first().innerText()).includes('等待成团') && await mobile.locator('#dialog .formation-block').first().evaluate(el => el.getBoundingClientRect().width <= innerWidth), '移动端成团状态完整显示且不溢出');
    await mobile.screenshot({ path: path.join(__dirname, 'formation-event-mobile.png'), fullPage: false });
    await mobile.locator('[data-action="close"]').last().click();
    await mobile.locator('[data-action="event"][data-id="e1"]').click();
    check(await mobile.locator('#dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth), '移动端任务简报不超出视口');
    check(await mobile.locator('.social-preview').evaluate(el => {
      const parse = value => (value.match(/[\d.]+/g) || []).slice(0, 3).map(Number);
      const luminance = value => { const rgb = parse(value).map(channel => { const c = channel / 255; return c <= .03928 ? c / 12.92 : ((c + .055) / 1.055) ** 2.4; }); return .2126 * rgb[0] + .7152 * rgb[1] + .0722 * rgb[2]; };
      const style = getComputedStyle(el); const foreground = luminance(style.color); const background = luminance(style.backgroundColor); const ratio = (Math.max(foreground, background) + .05) / (Math.min(foreground, background) + .05);
      return ratio >= 4.5;
    }), '移动端活动社交预览文字对比度至少达到 4.5:1');
    await mobile.screenshot({ path: path.join(__dirname, 'low-pressure-preview-mobile.png'), fullPage: false });
    await mobile.locator('[data-action="register"][data-id="e1"]').click();
    check(await mobile.locator('#action-feedback').evaluate(el => el.matches(':popover-open') && el.getBoundingClientRect().width <= innerWidth), '移动端角色反馈不超出视口');
    await mobile.waitForTimeout(450);
    await mobile.screenshot({ path: path.join(__dirname, 'feedback-mobile.png'), fullPage: false });
    await mobile.waitForFunction(() => !document.querySelector('#action-feedback').matches(':popover-open'), null, { timeout: 4500 });
    await mobile.screenshot({ path: path.join(__dirname, 'mission-mobile.png'), fullPage: false });
    await mobile.getByRole('button', { name: '活动回顾', exact: true }).click();
    await mobile.getByRole('button', { name: '创建活动回顾', exact: true }).click();
    check(await mobile.locator('#dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth), '移动端活动回顾编辑器不超出视口');
    await mobile.locator('#event-review-form [name="title"]').fill('移动端阅读测试');
    await mobile.locator('#event-review-form [name="summary"]').fill('这是一段用于验证移动端阅读体验的活动总结正文。');
    await mobile.locator('#event-review-form [name="highlights"]').fill('成员互动顺畅，现场反馈积极。');
    await mobile.locator('#event-review-form [name="suggestion"]').fill('下一次提前发布更清晰的集合说明。');
    await mobile.getByRole('button', { name: /提交发布审核/ }).click();
    await mobile.getByRole('button', { name: '打开阅读窗口', exact: true }).click();
    check(await mobile.locator('#dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth && el.scrollWidth <= innerWidth), '移动端活动回顾阅读窗口不超出视口');
    check(parseFloat(await mobile.locator('.reading-sheet section p').first().evaluate(el => getComputedStyle(el).fontSize)) >= 16, '移动端阅读窗口正文保持至少 16px');
    await mobile.screenshot({ path: path.join(__dirname, 'reading-window-mobile.png'), fullPage: false });
    await mobile.locator('[data-action="close"]').last().click();
    await switchPage(mobile, 'community');
    check(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '移动端同好页无横向溢出');
    check((await mobile.locator('.community-screen').evaluate(el => getComputedStyle(el).backgroundImage)).includes('bonds-collage.webp'), '移动端同好背景正常加载');
    await mobile.locator('[data-action="public-club"]').click();
    check(await mobile.locator('.public-club-dialog').count() === 1, '移动端公开社团主页加载');
    check(await mobile.locator('.public-club-dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth && el.scrollWidth <= innerWidth), '移动端公开主页不超出视口');
    check((await mobile.locator('.public-club-rules').innerText()).includes('示例数据不代表真实通知或权限'), '移动端公开主页演示边界可读');
    await mobile.screenshot({ path: path.join(__dirname, 'public-club-mobile.png'), fullPage: false });
    await mobile.locator('[data-action="close"]').last().click();    await mobile.locator('[data-action="group"][data-id="g1"]').click();
    await mobile.getByRole('button', { name: '共享文件', exact: true }).click();
    await mobile.locator('[data-action="file-upload-demo"]').click();
    await mobile.getByRole('button', { name: '建立演示上传任务', exact: true }).click();
    await mobile.getByRole('button', { name: '模拟进入传输进度', exact: true }).click();
    check(await mobile.locator('#dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth && el.scrollWidth <= innerWidth), '移动端上传流程外壳不超出 390px 视口');
    check(await mobile.locator('.upload-stage-card').evaluate(el => el.getBoundingClientRect().right <= innerWidth && el.getBoundingClientRect().left >= 0), '移动端上传阶段卡片完整可见');
    check(await mobile.locator('#dialog input[type="file"]').count() === 0, '移动端上传流程同样不会读取真实文件');
    await mobile.screenshot({ path: path.join(__dirname, 'upload-flow-mobile.png'), fullPage: false });
    await mobile.locator('[data-action="close"]').last().click();
    for (let gameIndex = 0; gameIndex < 6; gameIndex += 1) {
      const gameChip = mobile.locator('.game-chip').nth(gameIndex);
      const gameName = (await gameChip.locator('b').innerText()).trim();
      await gameChip.click();
      check(await mobile.locator('#dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth), `移动端${gameName}专区不超出视口`);
      await mobile.locator('[data-action="game-meet"]').first().click();
      check((await mobile.locator('.gathering-context').innerText()).includes(`${gameName} · 组队小聚`), `移动端${gameName}上下文来源正确`);
      check(await mobile.locator('#gathering-form input[name="title"]').inputValue() === `${gameName}组队行动` && await mobile.locator('#gathering-form input[name="place"]').inputValue() === '线上集合（社团内部）', `移动端${gameName}标题与地点预填正确`);
      await mobile.locator('#gathering-form input[name="title"]').fill(`${gameName}移动端行动`);
      await mobile.locator('#gathering-form input[name="place"]').fill('移动端线上房间（示例）');
      check(await mobile.locator('#gathering-form input[name="title"]').inputValue() === `${gameName}移动端行动` && await mobile.locator('#gathering-form input[name="place"]').inputValue() === '移动端线上房间（示例）', `移动端${gameName}预填字段可编辑`);
      await mobile.locator('[data-action="close"]').last().click();
    }    await mobile.locator('.game-chip').first().click();
    check(await mobile.locator('#dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth), '移动端游戏专区不超出视口');
    check(await mobile.locator('.game-tabs button').count() === 5, '移动端游戏专区分区完整');
    await mobile.screenshot({ path: path.join(__dirname, 'game-mobile.png'), fullPage: false });
    await mobile.locator('[data-action="close"]').last().click();
    await mobile.locator('[data-action="places"]').click();
    check(await mobile.locator('#dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth), '移动端校园手册不超出视口');
    check(await mobile.locator('.campus-card').count() === 4, '移动端校园地点卡片完整');
    await mobile.screenshot({ path: path.join(__dirname, 'campus-mobile.png'), fullPage: false });
    await mobile.locator('[data-action="close"]').last().click();
    await switchPage(mobile, 'me');
    check(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '移动端档案页无横向溢出');
    check((await mobile.locator('.me-screen').evaluate(el => getComputedStyle(el).backgroundImage)).includes('profile-dossier.webp'), '移动端档案背景正常加载');
    await mobile.screenshot({ path: path.join(__dirname, 'mobile.png'), fullPage: true });
    await mobile.locator('[data-action="leader-console"]').click();
    check(await mobile.locator('#dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth), '移动端社长工作台不超出视口');
    check(await mobile.locator('.leader-tabs button').count() === 6, '移动端工作台分区完整');
    await mobile.getByRole('button', { name: '成员管理', exact: true }).click();
    await mobile.locator('[data-action="application-decision"][data-id$=":approve"]').first().click();
    check(await mobile.locator('#application-last-result').evaluate(el => el.getBoundingClientRect().right <= innerWidth && el.getBoundingClientRect().left >= 0), '390px 管理完成回执不超出视口');
    check(await mobile.locator('#dialog').evaluate(el => el.scrollWidth <= innerWidth), '移动端成员管理与轻量状态无横向裁切');
    await mobile.locator('#application-last-result').scrollIntoViewIfNeeded();
    await mobile.screenshot({ path: path.join(__dirname, 'leader-mobile.png'), fullPage: false });
    await mobile.close();

    const inboxMobile = await open({ width: 390, height: 844 });
    await inboxMobile.locator('.mail').click();
    check(await inboxMobile.locator('#dialog').evaluate(el => el.getBoundingClientRect().width <= innerWidth && el.scrollWidth <= innerWidth), '移动端消息指挥板不超出视口');
    check(parseFloat(await inboxMobile.locator('.message-card p').first().evaluate(el => getComputedStyle(el).fontSize)) >= 14, '移动端消息摘要可读');
    check(await inboxMobile.locator('.message-head').evaluate(el => el.querySelector('p').getBoundingClientRect().right < el.querySelector('strong').getBoundingClientRect().left), '移动端消息标题区说明与未读数字不重叠');
    await inboxMobile.screenshot({ path: path.join(require('node:os').tmpdir(), 'p5-inbox-mobile.png') });
    await inboxMobile.locator('[data-action="message-filter"][data-id="小组"]').click();
    await inboxMobile.locator('[data-action="message-mark-visible"]').click();
    check(await inboxMobile.locator('#message-batch-state').evaluate(el => el.getBoundingClientRect().right <= innerWidth && el.getBoundingClientRect().left >= 0), '移动端内联 LOCKED 状态不超出 390px 视口');
    await inboxMobile.screenshot({ path: path.join(require('node:os').tmpdir(), 'p5-state-system-mobile.png'), fullPage: false });
    await inboxMobile.locator('[data-action="message-detail"][data-id="sample-group"]').click();
    check(parseFloat(await inboxMobile.locator('.message-reading section p').evaluate(el => getComputedStyle(el).fontSize)) >= 16, '移动端消息详情正文至少 16px');
    check(await inboxMobile.locator('#dialog').evaluate(el => el.scrollWidth <= innerWidth), '移动端消息阅读窗口无横向裁切');
    await inboxMobile.screenshot({ path: path.join(require('node:os').tmpdir(), 'p5-inbox-reading-mobile.png') });
    await inboxMobile.close();
    const localMissing = failedRequests.filter(item => item.startsWith('file:') && !item.endsWith(':: net::ERR_ABORTED'));
    check(localMissing.length === 0, `本地图片、视频与字体无加载失败${localMissing.length ? `: ${localMissing.join('; ')}` : ''}`);
    check(errors.length === 0, `浏览器脚本无异常${errors.length ? `: ${errors.join('; ')}` : ''}`);
    check(fs.statSync(path.join(__dirname, 'low-pressure-events-desktop.png')).size > 50000, '低压力活动页桌面截图已生成');
    check(fs.statSync(path.join(__dirname, 'low-pressure-preview-desktop.png')).size > 40000, '活动社交预览桌面截图已生成');
    check(fs.statSync(path.join(__dirname, 'low-pressure-events-mobile.png')).size > 30000, '低压力活动页移动截图已生成');
    check(fs.statSync(path.join(__dirname, 'low-pressure-preview-mobile.png')).size > 20000, '活动社交预览移动截图已生成');
    check(fs.statSync(path.join(__dirname, 'formation-event-desktop.png')).size > 30000, '成团状态桌面截图已生成');
    check(fs.statSync(path.join(__dirname, 'formation-form-desktop.png')).size > 30000, '低压力活动表单桌面截图已生成');
    check(fs.statSync(path.join(__dirname, 'formation-event-mobile.png')).size > 20000, '成团状态移动截图已生成');
    check(fs.statSync(path.join(__dirname, 'formation-form-mobile.png')).size > 20000, '低压力活动表单移动截图已生成');
    check(fs.statSync(path.join(__dirname, 'desktop.png')).size > 100000, '桌面截图已生成');
    check(fs.statSync(path.join(__dirname, 'mobile.png')).size > 50000, '移动截图已生成');
    check(fs.statSync(path.join(__dirname, 'transition.png')).size > 20000, 'PPT 转场截图已生成');
    check(fs.statSync(path.join(__dirname, 'page-intro-desktop.png')).size > 30000, '桌面页面进入提示截图已生成');
    check(fs.statSync(path.join(__dirname, 'page-intro-mobile.png')).size > 20000, '移动页面进入提示截图已生成');
    check(fs.statSync(path.join(__dirname, 'mission-detail.png')).size > 50000, '活动任务简报截图已生成');
    check(fs.statSync(path.join(__dirname, 'group-hub.png')).size > 50000, '小组内部据点截图已生成');
    check(fs.statSync(path.join(__dirname, 'mission-mobile.png')).size > 30000, '移动任务简报截图已生成');
    check(fs.statSync(path.join(__dirname, 'campus-guide.png')).size > 50000, '校园生活作战手册截图已生成');
    check(fs.statSync(path.join(__dirname, 'campus-mobile.png')).size > 30000, '移动校园生活作战手册截图已生成');
    check(fs.statSync(path.join(__dirname, 'game-zone.png')).size > 50000, '游戏专区截图已生成');
    check(fs.statSync(path.join(__dirname, 'game-mobile.png')).size > 30000, '移动游戏专区截图已生成');
    check(fs.statSync(path.join(__dirname, 'leader-console.png')).size > 50000, '社长工作台桌面截图已生成');
    check(fs.statSync(path.join(__dirname, 'leader-mobile.png')).size > 30000, '社长工作台移动截图已生成');
    check(fs.statSync(path.join(__dirname, 'management-states.png')).size > 30000, '管理完成态桌面截图已生成');
    check(fs.statSync(path.join(__dirname, 'review-editor.png')).size > 30000, '活动回顾编辑器截图已生成');
    check(fs.statSync(path.join(__dirname, 'reading-window-mobile.png')).size > 20000, '移动端大字号阅读窗口截图已生成');
    check(fs.statSync(path.join(__dirname, 'feedback-signup.png')).size > 50000, '桌面角色反馈截图已生成');
    check(fs.statSync(path.join(__dirname, 'feedback-mobile.png')).size > 30000, '移动角色反馈截图已生成');
    check(fs.statSync(path.join(__dirname, 'empty-state.png')).size > 30000, '角色空状态截图已生成');
    check(fs.statSync(path.join(__dirname, 'upload-flow-desktop.png')).size > 40000, '桌面上传流程外壳截图已生成');
    check(fs.statSync(path.join(__dirname, 'upload-flow-mobile.png')).size > 25000, '移动上传流程外壳截图已生成');

    console.log(`ALL ${checks} CHECKS PASSED`);
    await page.close();
  } finally {
    await browser.close();
  }
})().catch(error => {
  console.error(error.stack || error);
  process.exitCode = 1;
});





















